### ISSUE TITLE
Final stage of milestone2 

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/DSCI_522_BlackFriday_Analysis#29]
I have organized the entire file and generate our final report.

Would you please proofread our report?  After you proofread the report, we have serval things to do.
1. add one more reference to the report.
2. add a high-level summary to the main README.md file.
3. add a flow chart or explanation of how to run our analysis.

I am currently working on 3.

**Comment by gilbertlei** [comment]
I will do the proofreading and work on 1 & 2.

**Comment by gilbertlei** [comment]
I think it's better to do proofreading after we have finished all the pieces. Let's finish first the three things you mentioned above. what do you think?

**Comment by mru4913** [comment]
Sure

**Comment by gilbertlei** [comment]
I just updated the Reference section of Report.Rmd and added project execution summary to README. please check and merge.
